const TermsEnglish = () => {
  return (
    <div className="min-h-screen bg-gray-100 flex items-center justify-center p-6">
      <div className="bg-white shadow-md rounded-lg max-w-3xl w-full p-6">
        <h1 className="text-3xl font-bold text-blue-500 mb-4 text-center">
          Terms and Conditions
        </h1>
        <p className="text-gray-700 mb-4">
          Thank you for using <strong>InvoiceApp</strong>, a platform created
          for personal and educational purposes. Before using the platform, it
          is important that you read and accept the following terms and
          conditions. By using InvoiceApp, you acknowledge and accept the
          provisions described below:
        </p>
        <ol className="list-decimal list-inside text-gray-700 space-y-3">
          <li>
            <strong>Use of the platform at your own risk: {" "}</strong>
            InvoiceApp is a personal project, and although significant efforts
            have been made to ensure its proper functioning,
            <strong> {" "}
              we do not guarantee the accuracy or reliability of calculations
              performed by the platform
            </strong>
            . Users agree that it is their responsibility to verify the accuracy
            of the generated data, and any use of it will be at their own risk.
          </li>
          <li>
            <strong>Service availability: {" "}</strong>
            InvoiceApp is a project that may be{" "}
            <strong>
              temporarily or permanently offline without prior notice
            </strong>
            . We do not guarantee the continuous availability of the platform or
            the immediate resolution of technical problems.
          </li>
          <li>
            <strong>Data storage: {" "}</strong>
            InvoiceApp does not ensure the permanent storage of data uploaded or
            generated by users. Therefore, users accept responsibility for{" "}
            <strong>
              downloading and saving their own invoices or relevant data locally
            </strong>
            .
          </li>
          <li>
            <strong>Changes in design and processes: {" "}</strong>
            The platform is constantly evolving, and{" "}
            <strong>
              changes in design, functionality, or processes may occur without
              prior notice
            </strong>
            . This includes modifications that may affect how users interact
            with the platform.
          </li>
          <li>
            <strong>Exclusion of liability: {" "}</strong>
            InvoiceApp is not responsible for direct or indirect damages that
            may result from the use of the platform, including data loss,
            calculation errors, service interruptions, or any other
            inconvenience that may arise.
          </li>
          <li>
            <strong>Acceptance of risks: {" "}</strong>
            By using InvoiceApp, you agree to understand and accept the risks
            associated with using a personal project, including potential
            failures, data loss, or functionality errors.
          </li>
          <li>
            <strong>Modification of terms and conditions: {" "}</strong>
            We reserve the right to modify these terms and conditions at any
            time without prior notice. The latest version will always be
            available on the platform, and it is the users responsibility to
            review it periodically.
          </li>
        </ol>
        <p className="text-gray-700 mt-6 text-center">
          If you have questions or need more information, please contact the
          platform administrator.
        </p>
      </div>
    </div>
  );
};
export default TermsEnglish;
